### ISSUE TITLE
False information about how LibreSignal works

### ISSUE THREAD

**Issue by mimi89999** [Kajisav/dephekt_blog#2]
> "Since you modified the original Signal code so much when making LibreSignal, you now realize your app doesn’t communicate with the official OWS Signal servers. Perhaps if the servers were modified, they could be made to work with your changes, but the point is it would require modifications which have an impact on developer time, maintenance costs, and take away from higher priority issues being addressed in a timely manner, the costs of which are disproportionately borne by OWS."

OWS Signal servers do support WebSocket (what LS is using for receiving messages without GCM). LS does work with Signal servers. The server code doesn't need to be modified. Also, LS doesn't use any own/custom servers. You can send and receive messages to/from "vanilla" Signal users.

What doesn't work is LS with the RedPhone servers (for voice calls).

Also, what is important is not only the metadata over GCM, but the fact, that gapps run with system app privileges and Google can for example update, install or remove user apps without user interaction...

**Comment by Kajisav** [comment]
Noted.
